# NUMPY - 
* it is a python library for numeric and scientific computing.
* it stand for numerical python and consists of multi - dimensional array objects.
* it is faster with less location.
* it allow you to perform various operations on Arrays, including.( arr slicing, arr join, arr split, arr reshape, arr filter)

# CREATE NUMPY ARRAYS - 
To create NumPy arrays, use ( numpy.array( ) or np.array( ) ) method in python. we can create arrays using any of the following ways:
* Create a NumPy array by passing Tuple
* Create a NumPy array by passing List

In [ ]:
## Array creating using tuples in NumPy. 

import numpy as np

n = np.array((1, 2, 3))      ## in curve brackets
print(type(n),n)


<class 'numpy.ndarray'> [1 2 3]


In [ ]:
## Array creating using List in NumPy.

import numpy as np

n = np.array([1, 2, 3])    ## in squre brackets
print(type(n), n)


<class 'numpy.ndarray'> [1 2 3]


# DIMENSIONS IN NUMPY ARRAYS-
dimensions of an array in Numpy are also called the Rank of an array. to check how many dimensions an array has used with the{ numpy.ndarray.ndim }( n.ndim )attribute.
* some exmaple of create a 0-D , 1-D, 2-D Numpy array.

In [ ]:
## Creating 0-D numpy array.

import numpy as np

n= np.array(45)
print(f"The dimension of array {n} is {n.ndim}-D")


The dimension of array 45 is 0-D


In [ ]:
## creating 1-D numpy array.

import numpy as np

n = np.array([1, 2, 3, 4, 5])

print(f"The Dimension of array {n} is {n.ndim}-D")


The Dimension of array [1 2 3 4 5] is 1-D


In [ ]:
## creating 2-D numpy array.

import numpy as np

n = np.array([[1, 2], 
              [3, 4], 
              [5,6]])

print(f"The Dimension of array \n {n} is {n.ndim}-D")


The Dimension of array 
 [[1 2]
 [3 4]
 [5 6]] is 2-D


# INITIALIZE NUMPY ARRAYS-
to initialize Numpy arrays, we can use the ( numpy.zeros( ) ) method. using this method, initialize Numpy arrays with zeros.

In [17]:
## initalize numpy array with zeros.

import numpy as np
n = np.zeros([3,3])  ## it take np.zeros([row, col])
print(n,type(n))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


# DATATYPES IN NUMPY-
supports datatypes- b-boolean, u-unsigned int, f-float, c-complex float, m-timedelta, M-datetime, O-object, S-string, U-unicode string.
* use (n.dtype)attribute. method to datatype.
* use ( astype( ) ) to create a copy of an array and then set the new data type. in this manner you convert one datatype into aother. in numpy.

In [ ]:
## Q.1 get the datatype of a Numpy array with integers.

import numpy as np

n = np.array([10, 20, 30])
print(f"the array {n} have Datatype {n.dtype}")       ## int64 array with integer show() 64 is device bit.


the array [10 20 30] have Datatype int64


In [ ]:
## Q.2 get the datatype of a Numpy array with strings.

import numpy as np

n = np.array(["Ajay", "Shakti", "Anu", "Kunal"])
print(f"the array {n} have Datatype {n.dtype}")           ## <U6 is U = Unicode String and 6 is max length of char(shakti) which you give in input.


the array ['Ajay' 'Shakti' 'Anu' 'Kunal'] have Datatype <U6


In [ ]:
## Q.3 set the datatype size(5) of a string within a Numpy array.

import numpy as np

n = np.array(["Ajay", "Shakti", "Anu", "Kunal"], dtype = 'S5') ## S5 means string size 5. although "shakti" have 6 char in it.
print(f"the array {n} have Datatype {n.dtype}")     


the array [b'Ajay' b'Shakt' b'Anu' b'Kunal'] have Datatype |S5


In [ ]:
## Q.4 covert one datatype to another.(in this we have a array of strings. we will convert it to an integer, with i as a parameter).

import numpy as np 
n = np.array(["10", "20", "30", "40", "50"])
print(n,n.dtype)         ## here U- Unicode string and max len of char of string.

n1 = n.astype('i')      ## here i - integer. or n.astype('i') --> convert U(unicode string) into i(integer).
print(n1,n1.dtype)


['10' '20' '30' '40' '50'] <U2
[10 20 30 40 50] int32


# NUMPY ARRAY INDEXING - 
array indexing is accessing array elements. In Numpy, access an array element using the index number. The index[0] = element 1 , index[1] = element 2 and so on...

In [ ]:
## access elements from a 1D Array.
import numpy as np

n = np.array([10, 20, 30, 40, 50])
print(n,n.ndim,"-D array")
print(n[0]) ## access the 1st element.
print(n[3]) ## access the 4th element.

k = int(input("enter the which (1-5)position element you want to access: "))
print(n[k-1])  ## access the kth element present at inndex[k-1].


[10 20 30 40 50] 1 -D array
10
40


enter the which (1-5)position element you want to access:  5


50


In [ ]:
## access elements from a 2D Array.
import numpy as np

n = np.array([[1,2,7],[3,4,8],[5,6,9]])
print(n,n.ndim,"-D array")
print(n[0,0],"= 1")       ## n[row,col] both starting from [0,0].
print(n[1,2],"= 4")
print(n[2,2],"= 8")


[[1 2 7]
 [3 4 8]
 [5 6 9]] 2 -D array
1 = 1
8 = 4
9 = 8


In [ ]:
## access elements from a 3D Array.(3D - consist of 2D arrays).
import numpy as np

n = np.array([[[1,2,9],      ## x = 0 ; y= 0-2 ; z = 0-2
               [3,4,10]],
              [[5,6,11],      ## x = 1 ; y= 0-2 ; z= 0-2
               [7,8,12]]])

print(n,n.ndim,"-D array") ## n[row,col] both starting from [0,0,0] , ending[1,1,2].
print(n[0,0,0],"= 1")
print(n[0,1,1],"= 4")
print(n[1,0,0],"= 5")
print(n[1,1,0],"= 7")
print(n[1,1,2],"= 12")
print(n[1,0,1],"= 6")


[[[ 1  2  9]
  [ 3  4 10]]

 [[ 5  6 11]
  [ 7  8 12]]] 3 -D array
1 = 1
4 = 4
5 = 5
7 = 7
12 = 12
6 = 6


In [ ]:
## access elements from the last with Negtive indexing.
import numpy as np

       ## x = -2 ; y,z= ([-3]-[-1])       ## x = -1 ; y,z= ([-3]-[-1])
n = np.array([ [ [1,2,9],[3,4,10] ] , [ [5,6,11],[7,8,12] ] ])

print(n, n.ndim,"-D array") ## n[row,col] both starting from [-2,-2,-3] , ending [-1,-1,-1]
print(n[-2,-2,-3],"= 1")
print(n[-2,-1,-2],"= 4")
print(n[-1,-2,-3],"= 5")
print(n[-1,-1,-3],"= 7")
print(n[-1,-1,-1],"= 12")
print(n[-1,-2,-2],"= 6")
print(n[-2,-2,-1],"= 9")


[[[ 1  2  9]
  [ 3  4 10]]

 [[ 5  6 11]
  [ 7  8 12]]] 3 -D array
1 = 1
4 = 4
5 = 5
7 = 7
12 = 12
6 = 6
9 = 9


# NUMPY SLICING IN (1-D) ARRAY- 
slicing the array in range from start to end is what we call Array slicing. Slice(range) is passed in place of index. syantax: - arr[ start : end ]
* here, start is (include) because starting from there but the end is (excluded) becoz starting from index 0 so it will go from 0 -(n-1) positions.
* SLICING with step - arr[ start : end : step ].


In [ ]:
## Q.1 Slicing from index 2 to 5 (5exculed)

import numpy as np

n = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

print(n[2: 5])


[15 20 25]


In [ ]:
## Q.2 Slicing from index 5 to last

n = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
k = len(n)

print(n[5: k+1])


[30 35 40 45 50]


In [ ]:
## Q.3 Slicing from starting to 5 (5 exculed) 
n = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

print(n[ : 5])


[ 5 10 15 20 25]


In [ ]:
## Q.4 Sliing from with jump/step is 2.

n = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

print(n[: : 2])  ## or n[0:10:2] starting from odd position
print(n[1:10:2])           ## starting from even position.


[ 5 15 25 35 45]
[10 20 30 40 50]


# NUMPY SLICING IN (2-D) ARRAY-
syntax - arr[(0/1) , start : end ]
* 2D slicing syntax : 
array[ row_start : row_end , col_start : col_end ]

In [ ]:
## Q.5 slicing from index 2 to 5(excluding 5)

n = np.array([ [5, 10, 15, 20, 25],   
              [30, 35, 40, 45, 50] ])

print(f"slicing in {n.ndim}D array\n")

## when print one row only.

print(n[0, 2:5])   ## n [(0/1) , start : end ]
print(n[1, 2:5 ]) 


slicing in 2D array

[15 20 25]
[40 45 50]


In [ ]:
## now let's combine both in one go.

n = np.array([ [5, 10, 15, 20, 25],   
              [30, 35, 40, 45, 50] ])

print(f"slicing in {n.ndim}D array\n")

## when print multiple row.

print(n[0:2, 2:5])       ## n[row_start:row_end, col_start:col_end] --> n[row 0 : row 2 , col 2 : col 5].


slicing in 2D array

[[15 20 25]
 [40 45 50]]


# NUMPY ARRAY SHAPE- 
it means the number of elements in each dimension of an array of an array is called the shape.  to get this shape use the ( numpy.shape ) attribute in python.

In [ ]:
## Q.1 check the shape of a 0-D numpy arr.

import numpy as np

n = np.array(10)
print(f"the array {n} of {n.ndim}-D have shape {n.shape}")


the array 10 of 0-D have shape ()


In [ ]:
## Q.2 check the shape of a 1-D numpy arr.

import numpy as np

n = np.array([10, 20, 30, 40, 50])
print(f"the array {n} of {n.ndim}-D have shape {n.shape}")  ## it will give the number of element of array(in row).


the array [10 20 30 40 50] of 1-D have shape (5,)


In [ ]:
## Q.3 check the shape of a 2-D 0numpy arr. / Matrix.

import numpy as np

n = np.array([[1,2,7,10],[3,4,8,11],[5,6,9,12]])
print(f"the array \n {n} of {n.ndim}-D have shape {n.shape}")  ## it will give the number of element of array(row, col).


the array 
 [[ 1  2  7 10]
 [ 3  4  8 11]
 [ 5  6  9 12]] of 2-D have shape (3, 4)


In [ ]:
## Q.4 check the shape of a 3-D numpy arr.

import numpy as np

n = np.array([ [ [1,2,9], [3,4,10] ] , [ [5,6,11],[7,8,12] ] ])
print(f"the array \n {n} of {n.ndim}-D have shape {n.shape}")  ## it will give the number of element of array( No_of_2Darr, 2Darr_row, 2D_col).


the array 
 [[[ 1  2  9]
  [ 3  4 10]]

 [[ 5  6 11]
  [ 7  8 12]]] of 3-D have shape (2, 2, 3)


# RESHAPE A NUMPY ARRAY-
in python numpy, the number od elements in each dimension of any array is called shape, to reshape the number of dimensions, use the [ numpy.reshape(row,col) ] method
* WHY RESHAPE? becoz
  reshape allow you to edit the number of elements in a dimension. addtionally, with reshape(), you can add or remove dimensions.

In [ ]:
## Q.5 reshape dimension from 1D - 2D.

import numpy as np
n = np.array([10, 20, 30, 40, 50, 60])     ## no of elements according to to matrix in which is convert.
print("the 1D array - ", n, n.ndim,'-D arr')

## Reshape.
reshape = n.reshape(2,3)  ## 2D array of 2 row and 3 col.
print("the array is reshaped - \n",reshape, reshape.ndim,'-D arr')


the 1D array -  [10 20 30 40 50 60] 1 -D arr
the array is reshaped - 
 [[10 20 30]
 [40 50 60]] 2 -D arr


In [ ]:
## Q.6 convert 3D array to 1D array (Flattening the array)

import numpy as np

n = np.array([ [ [1,2,9], [3,4,10] ] , [ [5,6,11],[7,8,12] ] ])
print("the 3D array - \n", n, n.ndim,'-D arr\n')

##Reshape.
reshape = n.reshape(-1)   ## this will reshape in 3D array in 1D array.
print("the array is reshaped - \n",reshape)


the 3D array - 
 [[[ 1  2  9]
  [ 3  4 10]]

 [[ 5  6 11]
  [ 7  8 12]]] 3 -D arr

the array is reshaped - 
 [ 1  2  9  3  4 10  5  6 11  7  8 12]


# ITERATE NUMPY ARRAYS -
iterate is displaying each element of an array.here iterate through numpy arr using loops and other methods.

In [ ]:
## Q.1 iterate a 1-D numpy arr.

import numpy as np
n = np.array([10, 20, 30, 40, 50, 60])

print("the iteration in 1-D arr is:")

for i in n:
    print(i,end=' ')


the iteration in 1-D arr is:
10 20 30 40 50 60 

In [8]:
## Q.2 iterate a 2-D numpy arr.

import numpy as np
n = np.array([[1,2,7,10],[3,4,8,11],[5,6,9,12]])

print(" the iteration in 2-D arr is: ")

for i in n:
    print(i)


 the iteration in 2-D arr is: 
[ 1  2  7 10]
[ 3  4  8 11]
[ 5  6  9 12]


In [ ]:
## Q.3 iterate a 3-D numpy arr.
import numpy as np
n = np.array([ [ [1,2,9], [3,4,10] ] , [ [5,6,11],[7,8,12] ] ])

print(" the iteration in 3-D arr is: ")

for i in n:
    print("there are 2D matrix in 3-D arr.\n",i)


 the iteration in 3-D arr is: 
there are 2D matrix in 3-D arr.
 [[ 1  2  9]
 [ 3  4 10]]
there are 2D matrix in 3-D arr.
 [[ 5  6 11]
 [ 7  8 12]]


# JOIN NUMPY ARRAYS- 
we can join two or more arrays in a single new array using the following:
1. concatenate() method: joining along with axis, unlike keys in SQL.
2. stack methods: joining along a new axis, unlike keys in SQL. ( stack(), hstack(), vstack(), dstack(), column_stack() )

In [ ]:
## by using 1st method.

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.concatenate((n1,n2)) ### use numpy.concatenate( (val1, val2) );   note - (val1,val2) must be in a new bracket.
print(result)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
## make result arr a natural number sequence.

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.concatenate((n1,n2)) ### use numpy.concatenate( (val1, val2) );   note - (val1,val2) must be in a new bracket.
result.sort()
print(result)


[ 1  2  3  4  5  6  7  8  9 10]


##  NOTE - IN all stack() methods - 
* all input arrays must have the same shape.  otherwise throug:  ValueError
* the stack() make two array in 2-D and by defult takes (0,0) indexing.
* the dstack() make the transpose of result of the stack() and vstack(). it means depth(height) convert len(arr) into height(arr) or M[col]-> M[row]
* the dstack() also make two arr in 3-D matrix.

In [22]:
## by using 2nd method. 

## stack() it will give the array in 2-D arr.

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.stack((n1, n2))  ## don't mention axis so by defult(0,0)
print(result)


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [30]:
## hstack() it used in stack along rows using the hstack(). in numpy. 

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.hstack((n1, n2))  # join along rows.
print(result)


[ 1  3  5  7  9  2  4  6  8 10]


In [ ]:
## vstack() it used in stack along columns using the vstack(). in numpy. 

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.vstack((n1, n2))  # join along columns.
print(result)


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [ ]:
## dstack() it used in stack along depth(height)  using the dstack(). in numpy. it will give 3-D arr.

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.dstack((n1, n2))  ## stack along rows of both arr.
print(result)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]


In [ ]:
## columns_stack() it used in stack according to  columns using the column_stack(). in numpy. 

import numpy as np

n1 = np.array([1,3,5,7,9])
n2 = np.array([2,4,6,8,10])

result = np.column_stack((n1, n2))  ## stack along colunns of both arr.
print(result)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# SPLIT NUMPY ARRAY- 
it is used to break/ slash an array into multiple arrays. used ( array_split() ) method.
* syantax - array_split(arr_name, split_num)  ** here arr_name =  name of the array. ; split_num = the num of parts want to splits.

In [ ]:
## Q.1 split a 1D array.

import numpy as np

n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

result = np.array_split(n1,2)
print(result)


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [ ]:
## Q.2 Access a split 1D array. using the index number for the array element you want to display.

import numpy as np

n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

result = np.array_split(n1,5)
print(result)
print("arr1 at index 0 ", result[0])     ## result[0] means "access the first part" (i.e., the array at index 0 in the list).
print("arr2 at index 1", result[1])      ## result[1] means "access the second part" (i.e., the array at index 1 in the list).
print("arr3 at index 2", result[4])      ## result[4] means "access the forth part" (i.e., the array at index 4 in the list).


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
arr1 at index 0  [1 2]
arr2 at index 1 [3 4]
arr3 at index 2 [ 9 10]


In [86]:
## Q.3 split a 2D array and how to access.

import numpy as np

n = np.array([ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] ])

result = np.array_split(n,2)
print("arr1 = ", result[0])
print("arr2 = ", result[1])


arr1 =  [[1 2 3 4 5]]
arr2 =  [[ 6  7  8  9 10]]


# SEARCH A NUMPY ARRAY FOR A SPECIFIC VALUE -
in a NUMPY arr, we can search for a specific value by using ( numpy.where( ) ) method. it return the index of that value which is present in array.

In [ ]:
import numpy as np        

n = np.array([12, 34, 65, 76, 94, 34])

print(n)
k = int(input("choose the element from the given arr you want to found index."))     ## if unique value

result = np.where(n == k)
print(f"the value {k} found at {result} index.")


[12 34 65 76 94 34]


choose the element you want to found index. 65


the value 65 found at (array([2]),) index.


In [72]:
k = int(input("choose the element from the given arr you want to found index."))      ## if same value at different locations.

result = np.where(n == k)
print(f"the value {k} found at {result} index.")


choose the element from the given arr you want to found index. 34


the value 34 found at (array([1, 5]),) index.


# SORTING NUMPY ARRAYS - 
the ( numpy.sort( ) ) function is used to sort arrays in a sequence. this sequence can be ascending or decending order.

In [ ]:
## Q.1 sort a 1-D integer Array

import numpy as np

n = np.array([12, 34, 65, 76, 94, 34])

print(np.sort(n))


[12 34 34 65 76 94]


In [ ]:
## Q.2 sort a 1-D string array

import numpy as np

n = np.array(['Delhi', 'aGra', 'Goa', 'jAndK', 'aMAzone', 'NAGA'])

print(np.sort(n))


['Delhi' 'Goa' 'NAGA' 'aGra' 'aMAzone' 'jAndK']


In [ ]:
## Q.3 sort a 2-D array

import numpy as np

n1 = np.array([ [1, 7, 0, 8, 5], [6, 3, 8, 2, 10] ])
print("Before sorting-\n", n1)
print("\nAfter sorting-\n",np.sort(n1))


Before sorting-
 [[ 1  7  0  8  5]
 [ 6  3  8  2 10]]

After sorting-
 [[ 0  1  5  7  8]
 [ 2  3  6  8 10]]


# AXES IN NUMPY ARRAYS -
the axis is the direction along the rows and columns. a 2D numpy arr has the following 2 crossesponding axes:
verticals axis (axis 0) - rows along
horizontal axis (axis 1) - col along

In [ ]:
import numpy as np

n = np.array([[1, 7, 0, 17] ,[8, 5, 6, 3] , [8, 2, 10, 1] ])

print(n)
print("minimum value = ", n.min() ) ## by defult from whole matrix.


[[ 1  7  0 17]
 [ 8  5  6  3]
 [ 8  2 10  1]]
minimum value =  0


# NUMPY - GET MINIMUM VALUE WITH AXES ->
specifying axes will calculate values along that specfic axes only. to understand the concept of axis and get the minimum value. we have used the min( ) method and the axis attribute :

In [92]:
import numpy as np

n = np.array([[1, 7, 0, 17] ,[8, 5, 6, 3] , [8, 2, 10, 1] ])

print(n)
print("minimum value = ", n.min() )
print("get minimum value with axes 0 for (vertical(col) axes): \n ", n.min(axis = 0 ))
print("get minimum value with axes 1 for (horizontal(row) axes): \n", n.min(axis = 1))


[[ 1  7  0 17]
 [ 8  5  6  3]
 [ 8  2 10  1]]
minimum value =  0
get minimum value with axes 0 for (vertical(col) axes): 
  [1 2 0 1]
get minimum value with axes 1 for (horizontal(row) axes): 
 [0 3 1]


# NUMPY ARRAYS INTERSECTION- 
for intersection of two arrays, use the ( intersect1d( ) ) method in Numpy. intersection means common element in both array.

In [ ]:
## Q.1 find the intersection between two arrays.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.intersect1d(n1,n2)

print("the first array: ", n1)
print("the second array: ", n2)
print("intersection of two arr: ", result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
intersection of two arr:  [6 8]


In [ ]:
## Q.2 finding tntersection between two unsorted arrays sorts the resultant array.

import numpy as np

n1 = np.array([2, 3, 85, 6, 100, 1, 4])
n2 = np. array([4, 7, 8, 12, 48, 100, 85])

result = np.intersect1d(n1, n2)

print("the first array: ", n1)
print("the second array: ", n2)
print("intersection of two arr. ", result)


the first array:  [  2   3  85   6 100   1   4]
the second array:  [  4   7   8  12  48 100  85]
intersection of two arr.  [  4  85 100]


In [ ]:
## Q.3 find the intersection between two arrays with different elements.


import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.intersect1d(n1,n2)

print("the first array: ", n1)
print("the second array: ", n2)
print("intersection of two arr: ", result)


the first array:  [1 2 3 4 5]
the second array:  [ 6  7  8  9 10]
intersection of two arr:  []


# NUMPY DIFFERENCE BETWEEN TWO ARRAYS -
to find the difference between two arrays, use the ( numpy.setdiff1d( ) ) method. it means the common elements of second array are deleted from first array.
* syntax np.setdiff1d(array1, array2)

In [ ]:
## Q.1 find the difference between two arrays. (n1 - n2).

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.setdiff1d(n1, n2)

print("the first array: ", n1)
print("the second array: ", n2)
print("difference of two arr", result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
difference of two arr [1 3 5]


In [ ]:
## Q.2 find the diffference between two arrays. when the input swap (n2 - n1).

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.setdiff1d(n2, n1)

print("the first array: ", n1)
print("the second array: ", n2)
print("difference of two arr ", result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
difference of two arr  [ 7  9 10]


# ARITHMETIC OPERATION ON NUMPY ARRAYS -
for perfomainging these opertion used ( sum([ ]), subtract([ ]), multiply([ ]), divide([ ])) methods.

## sum( ) method syntax - np.sum( [arr1, arr2] )

In [ ]:
## Q.1 for addition sum() method.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.sum([n1, n2])      ## by defult is gives addition along rows.

print("the first array: ", n1)
print("the second array: ", n2)
print("addition of two arr" ,result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
addition of two arr 63


In [ ]:
## Q.2 Add column values of numpy arrays using axis paramters.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.sum([n1, n2], axis = 0 )  ## axis = 0 for column value addition. 
print("the first array:", n1)
print("the second array:", n2)
print("addition of two arr along columns: ", result)

result = np.sum([n1, n2], axis = 1)   ## axis = 1 for row value addition. also by defult give along rows.
print("\nthe first array:", n1)
print("the second array:", n2)
print("addition of two arr along rows: ", result)


the first array: [1 6 3 8 5]
the second array: [ 6  7  8  9 10]
addition of two arr along columns:  [ 7 13 11 17 15]

the first array: [1 6 3 8 5]
the second array: [ 6  7  8  9 10]
addition of two arr along rows:  [23 40]


In [ ]:
## Q.3 Add individual array values using the axis paramter.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.sum([n1, n2], axis = 1)   ## axis = 1 for row value addition. also by defult give along rows.
print("\nthe first array:", n1)
print("the second array:", n2)
print("addition of two arr along rows: ", result)



the first array: [1 6 3 8 5]
the second array: [ 6  7  8  9 10]
addition of two arr along rows:  [23 40]


## subtract( ) method syntax - np.subtract( arr1, arr2 )

In [ ]:
## Q.1 for subtrection subtract() method.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.subtract(n1, n2)      ## by defult is gives subtraction along columns..

print("the first array: ", n1)
print("the second array: ", n2)
print("subtraction of two arr" ,result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
subtraction of two arr [-5 -1 -5 -1 -5]


## multiply( ) method syntax - np.multiply( arr1, arr2 )

In [ ]:
## Q.1 for Multiplying multiply() method.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.multiply(n1, n2)      ## by defult is gives multiply along columns.

print("the first array: ", n1)
print("the second array: ", n2)
print("subtraction of two arr" ,result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
subtraction of two arr [ 6 42 24 72 50]


## divide( ) method syntax- np.divide( arr1, arr2)

In [ ]:
## Q.1 for dividing divide() method.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

result = np.divide(n1, n2)      ## by defult is gives dividing along columns.

print("the first array: ", n1)
print("the second array: ", n2)
print("subtraction of two arr" ,result)


the first array:  [1 6 3 8 5]
the second array:  [ 6  7  8  9 10]
subtraction of two arr [0.16666667 0.85714286 0.375      0.88888889 0.5       ]


# NUMPY ARRAYS SCALAR OPERATIONS -
Scalar operations on numpy arr include performaing airthmatic operation on each element of numpy arr.

In [ ]:
## Q.1 Addition(+) operation on Numpy arrays.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

print("the first array before operation: ", n1)
print("the second array before operation:  ", n2)

n1 = n1 + 10
n2 = n2 + 10

print("\nthe first array after operation: ", n1)
print("the second array after operation:  ", n2)


the first array before operation:  [1 6 3 8 5]
the second array before operation:   [ 6  7  8  9 10]

the first array after operation:  [11 16 13 18 15]
the second array after operation:   [16 17 18 19 20]


In [ ]:
## Q.2 Subtraction(-) operation on Numpy arrays.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

print("the first array before operation: ", n1)
print("the second array before operation:  ", n2)

n1 = n1 - 10
n2 = n2 - 10

print("\nthe first array after operation: ", n1)
print("the second array after operation:  ", n2)


the first array before operation:  [1 6 3 8 5]
the second array before operation:   [ 6  7  8  9 10]

the first array after operation:  [-9 -4 -7 -2 -5]
the second array after operation:   [-4 -3 -2 -1  0]


In [42]:
## Q.3 Multiplication(*) operation on Numpy arrays.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

print("the first array before operation: ", n1)
print("the second array before operation:  ", n2)

n1 = n1 * 10
n2 = n2 * 10

print("\nthe first array after operation: ", n1)
print("the second array after operation:  ", n2)


the first array before operation:  [1 6 3 8 5]
the second array before operation:   [ 6  7  8  9 10]

the first array after operation:  [10 60 30 80 50]
the second array after operation:   [ 60  70  80  90 100]


In [ ]:
## Q.4 Division(/) operation on numpy arrays.

import numpy as np

n1 = np.array([1, 6, 3, 8, 5])
n2 = np.array([6, 7, 8, 9, 10])

print("the first array before operation: ", n1)
print("the second array before operation:  ", n2)

n1 = n1 / 10
n2 = n2 / 10

print("\nthe first array after operation: ", n1)
print("the second array after operation:  ", n2)


the first array before operation:  [1 6 3 8 5]
the second array before operation:   [ 6  7  8  9 10]

the first array after operation:  [0.1 0.6 0.3 0.8 0.5]
the second array after operation:   [0.6 0.7 0.8 0.9 1. ]


# STATISTICAL OPERATIONS ON NUMPY ARRAYS-
We can perform statistical operation like ( mean, median and standard deviation )on numpy arrays.
1. Mean: The average value of a dataset, calculated by summing all the numbers and dividing by the total count of values.
2. Median: The middle value in a sorted list of numbers. If the list has an even number of elements, it’s the average of the two middle values.
3. Standard Deviation (SD): A measure of how spread out the numbers are from the mean; a higher SD means more variation in the data.

In [ ]:
## Mean is the avg of the given values. to find mean used ( np.mean( arr) ) method. 

import numpy as np

n = np.array([5, 7, 8, 9, 10, 11])

result = np.mean(n)
print(result)


8.333333333333334


In [ ]:
## Median is the middle value of the given arr. to find median used ( np.medain( arr) ) method. 

import numpy as np

n = np.array([10, 20, 30, 40, 50])

result = np.median(n)

print(result)


30.0


In [ ]:
## standard Deviation is a measure of how spread out the number are from the mean of given values. to find mean used ( np.std( arr) ) method. 

import numpy as np

n = np.array([10, 20, 30, 40, 50])

result = np.std(n)
print(result)


14.142135623730951


# RANDOM MODULE IN NUMPY -
* to work with random number, there is a module called Random.->  from numpy import random
* we used ( randint( ) ) method of the random module.
* used size( ) attribute to get a fixed size of aaray by calling this method -> random.randint( range, size = ( ) )
* used choice( arr ) from which you print any number randomaly but from the given arr. -> random.choice( arr )

In [3]:
## Q.1 generate a random number.

from numpy import random

n = random.randint(0,100)

print("every time you run this code get different random number between 0-100 like: " , n)


every time you run this code get different random number between 0-100 like:  66


In [ ]:
## Q.2 generate a random array with a fixed size. by using size parameter.

from numpy import random

## get the random number from 0-100. of fixed size arr of sized = 20.

n = random.randint(100, size = (20))   ## by defult give value in arr.

print("fixed size arr of sized = 20  from 0-100 : ",n)


fixed size arr of sized = 20  from 0-100 :  [33 84 41 60 24 48 91 28 44 46  7 15 36 37 65 99 47 17 69 88]


In [6]:
## Q.3 generate one of the random values based on an array of values by using choice( ) method.

from numpy import random

## geting the random element from a given arr.

result = random.choice([79, 39, 36, 32, 4, 2, 41, 61, 42, 13, 93, 93, 65, 93, 2, 95, 57, 44, 37, 89])

print(f"geting any random element from a given arr:{n} = ",result)


geting any random element from a given arr:[33 84 41 60 24 48 91 28 44 46  7 15 36 37 65 99 47 17 69 88] =  89


# NUMPY LOGS -
python numpy has some predefine function to work with Logs, such as numpy.log2( ), and numpy.log10( ), etc.

In [9]:
## example of np.log2()

import numpy as np

n = np.array([1, 2, 3, 4, 5])

print(f"the arr is {n} and the log2 of arr is {np.log2(n)}")


the arr is [1 2 3 4 5] and the log2 of arr is [0.         1.         1.5849625  2.         2.32192809]


In [ ]:
## example of np.log10()

import numpy as np

n = np.array([1, 2, 3, 4, 5])

print(f"the arr is {n} and the log2 of arr is {np.log10(n)}")


the arr is [1 2 3 4 5] and the log2 of arr is [0.         0.30103    0.47712125 0.60205999 0.69897   ]


# NUMPY LCM & HCF(GCD)-
To find LCM AND HCF of two numbers in Numpy. by using numpy.lcm( ) for LCM and numpy.gcd( ) for HCF(GCD).

In [ ]:
## Example of LCM

import numpy as np

a = int(input("enter the number1: "))
b = int(input("enter the number2: "))

result = np.lcm(a,b)   ## give indiviusal number.
print("the LCM of a, b: ",result)


enter the number1:  3
enter the number2:  7


the LCM of a, b:  21


In [18]:
## Exmaple of LCM when more then 2 arrguments.

import numpy as np

a = int(input("Enter the number1: "))
b = int(input("Enter the number2: "))
c = int(input("Enter the number3: "))

# Compute LCM of a and b, then compute LCM of that result with c. becoz np.lcm take only 2 arrgument.

result = np.lcm.reduce([a, b, c])
print("LCM of the numbers is:", result)


Enter the number1:  3
Enter the number2:  5
Enter the number3:  7


LCM of the numbers is: 105


In [ ]:
## Example of HCF(GCD)
import numpy as np

a = int(input("enter the number1: "))
b = int(input("enter the number2: "))

result = np.gcd(a,b)   ## give indiviusal number.
print("the HCF(GCD) of a, b: ",result)


enter the number1:  35
enter the number2:  42


the HCF(GCD) of a, b:  7


In [ ]:
## Exmaple of HCF(GCD) when more then 2 arrguments.
import numpy as np

a = int(input("Enter the number1: "))
b = int(input("Enter the number2: "))
c = int(input("Enter the number3: "))

# Compute LCM of a and b, then compute LCM of that result with c. becoz np.lcm take only 2 arrgument.

result = np.gcd.reduce([a, b, c])

print("LCM of the numbers is:", result)


Enter the number1:  105
Enter the number2:  91
Enter the number3:  23


LCM of the numbers is: 1
